name: Build and Deploy Extensions

on: 
  workflow_dispatch:
    inputs:
      isNightly:
        description: 'Is this a nightly build?'
        type: boolean
        required: true
        default: false

  workflow_call:
    inputs:
      isNightly:
        type: boolean
        description: 'Is this a nightly build?'
        required: true
        default: false

jobs:
  call-workflow:
    uses: gorgonzola-graph-db/gorgonzola-workflows/.github/workflows/build-and-deploy-extension.yml@master
    secrets: inherit
